### ISSUE TITLE
Publish a docker image

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/zeebe-cherry-runtime#70]
A collection should be available somewhere as a docker image, and then it can be used in a docker-compose.
How to specify then the Zeebe connection? Two options:
1/ as some configuration variables
2/ as an administrative page (attention, any password must be hidden - the user can change it but not see it.

Note: must be an environment variable to HIDE the administration page. A configuration may want to set up the connection via the configuration variable and want to not display that configuration or not be able to change it at all.

**Comment by jonathanlukas** [comment]
As you are using spring-boot, all demands are already satisfied with the framework itself. There are several ways to enhance the given properties, so docker images built with a spring boot app are very configurable.
As your description overlaps a bit with #69, I would go for a solution there that suits later dockerization.

**Comment by pierre-yves-monnet** [comment]
Done, image is now published
